# Basic Air configuration
[build]
cmd = "go build -o ./tmp/main.exe -buildvcs=false ."
bin = "./tmp/main.exe"
full_bin = "./tmp/main.exe"
include_ext = ["go", "tpl", "html", "css"]
exclude_dir = ["tmp", "vendor"]
exclude_file = ["*.test.go"]
delay = 1000
log = "air.log"
stop_on_error = true
buildvcs = false

[log]
color = true
timestamp = false
